// This file would normally be auto-generated by Supabase
// For demo purposes, we'll define key database types here

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string
          clerk_id: string | null
          email: string
          user_type: 'user' | 'professional' | 'admin' | 'moderator'
          created_at: string
          updated_at: string
        }
        Insert: Omit<Database['public']['Tables']['profiles']['Row'], 'id' | 'created_at' | 'updated_at'>
        Update: Partial<Database['public']['Tables']['profiles']['Insert']>
      }
    }
  }
  legal: {
    Tables: {
      lg_questions: {
        Row: {
          id: string
          slug: string
          title: string
          body: string
          category: string
          subcategory: string
          keywords: string[]
          ai_summary: string | null
          complexity: string
          ai_quality_score: number | null
          moderation_passed: boolean
          created_at: string
          updated_at: string
        }
      }
    }
  }
}